# This files contains the matching rules that Alien 4 Cloud is going to apply to the nodes of an openstack location.
matching_configurations:
  alien.cloudify.aws.nodes.Compute:
    capabilities:
      - host:
          properties:
            - num_cpus: { less_or_equal: 0 } # we match if the template value is less or equal that the location resource value
            - cpu_frequency: { less_or_equal: 0 Hz }
            - mem_size: { less_or_equal: 0 B }
            - disk_size: { less_or_equal: 0 B }
      - os:
          properties:
            - architecture: { equal: "" }
            - type: { equal: "" }
            - distribution: { equal: "" }
            - version: { less_or_equal: "" }
  alien.cloudify.aws.nodes.WindowsCompute:
    capabilities:
      - host:
          properties:
            - num_cpus: { less_or_equal: 0 } # we match if the template value is less or equal that the location resource value
            - cpu_frequency: { less_or_equal: 0 Hz }
            - mem_size: { less_or_equal: 0 B }
            - disk_size: { less_or_equal: 0 B }
      - os:
          properties:
            - architecture: { equal: "" }
            - type: { equal: "" }
            - distribution: { equal: "" }
            - version: { less_or_equal: "" }
  alien.cloudify.aws.nodes.DeletableVolume:
    properties:
        - size: { less_or_equal: 0 B }
  alien.cloudify.aws.nodes.Volume:
    properties:
        - size: { less_or_equal: 0 B }

